---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/esoesdes/public_html/
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp -R wp-admin $DEPLOYPATH
    - /bin/cp -R wp-content $DEPLOYPATH
    - /bin/cp -R wp-includes $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
